@OrderProcessing_HostAddress = http://localhost:8080

GET {{OrderProcessing_HostAddress}}/guid
Accept: application/json

###

POST {{OrderProcessing_HostAddress}}/order
Content-Type: application/json

{
  "id": "9b5e87f8-b057-4180-8974-48bb5420dd13",
  "customerId": 55,
  "items": [
    {
      "productId": "premium-room",
      "quantity": 1
    },
    {
      "productId": "standard-room",
      "quantity": 2
    }
  ]
}


###
GET {{OrderProcessing_HostAddress}}/order/9b5e87f8-b057-4180-8974-48bb5420dd13
Accept: application/json

###
GET {{OrderProcessing_HostAddress}}/stats
Accept: application/json

